export const chanceCardList=[
    {title:'Advance to Go (Collect $200)'},
    {title:'Advance to Trafalgar Square. If you pass Go, collect $200'},
    {title:'Advance to Mayfair'},
    {title:'Advance to Pall Mall. If you pass Go, collect $200'},
    {title:'Advance to the nearest Station. If unowned, you may buy it from the Bank. If owned, pay wonder twice the rental to which they are otherwise entitled'},
    {title:'Advance to the nearest Station. If unowned, you may buy it from the Bank. If owned, pay wonder twice the rental to which they are otherwise entitled'},
    {title:'Advance token to nearest Utility. If unowned, you may buy it from the Bank. If owned, throw dice and pay owner a total ten times amount thrown.'},
    {title:'Bank pays you dividend of $50'},
    {title:'Get Out of Jail Free'},
    {title:'Go Back 3 Spaces'},
    {title:'Go to Jail. Go directly to Jail, do not pass Go, do not collect $200'},
    {title:'Make general repairs on all your property. For each house pay $25. For each hotel pay $100'},
    {title:'Speeding fine $15'},
    {title:'Take a trip to Kings Cross Station. If you pass Go, collect $200'},
    {title:'You have been elected Chairman of the Board. Pay each player $50'},
    {title:'Your building loan matures. Collect $150'},
]

export const communityChestCardList=[
    {title:'Advance to Go (Collect $200)'},
    {title:'Bank error in your favour. Collect $200'},
    {title:'Doctor\'s fee. Pay $50'},
    {title:'From sale of stock you get $50'},
    {title:'Get Out of Jail Free'},
    {title:'Go to Jail. Go directly to jail, do not pass Go, do not collect $200'},
    {title:'Holiday fund matures. Receive $100'},
    {title:'Income tax refund. Collect $20'},
    {title:'It is your birthday. Collect $10 from every player'},
    {title:'Life insurance matures. Collect $100'},
    {title:'Pay hospital fees of $100'},
    {title:'Pay school fees of $50'},
    {title:'Receive $25 consultancy fee'},
    {title:'You are assessed for street repairs. $40 per house. $115 per hotel'},
    {title:'You have won second prize in a beauty contest. Collect $10'},
    {title:'You inherit $100'},
]